### ISSUE TITLE
QueryError: Unable to put(): the given archive is not owned by this user

### ISSUE THREAD

**Issue by brettneese** [beakerbrowser/webdb#21]
Sorry if this is a rather silly question, but I'm trying out the examples - I've got a `/data` directory and I've ran `dat create` and `dat share` in it. But I get "QueryError: Unable to put(): the given archive is not owned by this user" when I run:

```
const DatArchive = require("node-dat-archive");
const WebDB = require("@beaker/webdb");
const assert = require("assert");
var webdb = new WebDB("./data", { DatArchive });

webdb.define("people", {
  // validate required attributes before indexing
  validate(record) {
    assert(record.firstName && typeof record.firstName === "string");
    assert(record.lastName && typeof record.lastName === "string");
    return true;
  },

  // secondary indexes for fast queries (optional)
  index: ["lastName", "lastName+firstName", "age"],

  // files to index
  filePattern: ["/person.json", "/people/*.json"]
});

const doStuff = async () => {
  await webdb.open();
  await webdb.indexArchive('dat://<urlFromDatShare>')

  await webdb.people.upsert(
    "dat://<UrlFromDatShare>/bob.json",
    {
      firstName: "Bob",
      lastName: "Roberts",
      age: 32
    }
  );

  var mrRoberts = await webdb.people.get("lastName", "Roberts");
};

doStuff();
```
How do I specify that I own this dat? What silly thing am I doing wrong?

**Comment by pfrazee** [comment]
Try loading the archive manually and then passing it to webdb. Eg:

```js
var archive = await DatArchive.load({
  localPath: './data',
  datOptions: {latest: true}
})
await webdb.indexArchive(archive)
```

**Comment by brettneese** [comment]
@pfrazee  Thanks! This makes more sense now; wasn't terribly clear how `node-dat-archive` and `webdb` fit together. 

For future Googlers/issue-peepers: doing that alone wasn't enough;  I ran into some issues with indexing when I tried to `put`; so I had to delete the directory and run 

```
var archive = await DatArchive.create({
    localPath: './data',
    datOptions: {latest: true}
  })
`

first. From then on I updated the example file to simply run `DatArchive.load()`. A full example (minus the archive creation):

```
const DatArchive = require("node-dat-archive");
const WebDB = require("@beaker/webdb");
const webdb = new WebDB("./index", { DatArchive });

webdb.define("foo", {
  schema: {
    type: "object",
    properties: {
      foo: { type: "string" }
    }
  },
  filePattern: ["/*.json"]
});

async function main() {
  var archive = await DatArchive.load({
    localPath: "./data",
    datOptions: { latest: true }
  });

  await webdb.open();
  await webdb.indexArchive(archive);

  await webdb.foo.upsert(`${archive.url}/foo.json`, { foo: "bar" });

  var bar = await webdb.foo.get(`${archive.url}/foo.json`);

  console.log(foo);
}

main();
```

Still a little unsure how this is going to work when I put the script I'm working on on a server and attempt to sync the data, but I'm closing this for now.

**Comment by pfrazee** [comment]
Yeah it is a little awkward. We need to improve the clarity of using WebDB with node-dat-archive

**Comment by DavidBernal** [comment]
Sorry for the question, but is this possible to use in beaker browser or is only for node?

I'm trying to create a DatArchive following @brettneese example and I get a prototype error related with fs.readStream.
