### ISSUE TITLE
Best way to handle ids/file names.

### ISSUE THREAD

**Issue by knownasilya** [beakerbrowser/webdb#32]
I'm looking to add many records for a table, so `people/*.json`. Should I manually define the id, like:

```js
import { v4 } from 'uuid';

await webdb.people.put(`dat://myaccount.hashbase.io/people/${v4()}.json`, {
  firstName: 'Bob',
  lastName: 'Roberts',
  age: 31
});
```

Or is there a better way to do that? Also, how do you automatically create the folder?

**Comment by pfrazee** [comment]
That looks right. You'll have to create the folder yourself (ie `archive.mkdir('/people')`).

**Comment by knownasilya** [comment]
Where do I get `archive`?

**Comment by pfrazee** [comment]
If you're in Beaker, you can do

```js
var archive = new DatArchive('dat://myaccount.hashbase.io')
```

Substitute whatever the URL of the dat is. You'll only be able to modify the archive (or put records on it via webdb) if you are its "owner."

**Comment by knownasilya** [comment]
Thanks! 😁

**Comment by knownasilya** [comment]
Last few questions.

How do I know if I can write to an archive?
And, how can I check if the directory doesn't exist? Or can I call mkdir either way and it'll just be a noop?

**Comment by pfrazee** [comment]
`archive.getInfo()` will return an object with `isOwner === true` if you can write to it

And yeah, you can just run the mkdir and ignore the error
