### ISSUE TITLE
Question about the README examples: do they modify another's Dat?

### ISSUE THREAD

**Issue by aaronshaf** [beakerbrowser/webdb#4]
In the CRUD examples on `bobsUrl`, is another person's dat being modified? I assume not, but it's not clear to me. 

Take for example:

```javascript
await db.profiles.update(bobsUrl, {name: 'robert'})
```

What is this doing? Is it updating a profile json file on a Dat from another source?

**Comment by pfrazee** [comment]
In that example, the profile.json on the archive called "bob" is getting changed.

**Comment by aaronshaf** [comment]
An archived "owned" by who?

**Comment by pfrazee** [comment]
The local user. You can change any archive you own, and you can own multiple archives.

(To be clear, "ownership" means you have the private key of the archive.)
