### ISSUE TITLE
It would be nice if `table.put()` returned the preprocessed/serialized record which will be inserted.

### ISSUE THREAD

**Issue by lachenmayer** [beakerbrowser/webdb#8]
My usecase: I'm adding some timestamps when serializing, and it would be nice to be able to return those from my API.

Should be a one-line change from what I can tell! :)

**Comment by lachenmayer** [comment]
Actually, never mind! Realised that it returns the URL while reading the tests, which is good enough.
This should be updated in the docs, they say it returns `Promise<void>`.
https://github.com/beakerbrowser/webdb#tableputurl-record

**Comment by pfrazee** [comment]
Ah yes, thanks. Will fix now.

**Comment by pfrazee** [comment]
Docs updated. Closing!
